[package]
name = "codecrafters-redis"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2024"

[dependencies]
anyhow = "1.0.59"                                   # error handling
#bytes = "1.3.0"                                     # helps manage buffers
#thiserror = "2.0.21"                                # error handling
#tokio = { version = "1.23.0", features = ["full"] } # async networking

[lints.clippy]
too_many_lines = "warn"
cognitive_complexity = "warn"
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"

[lints.rust]
missing_docs = "deny"